import Image from "next/image";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en h-full">
      <body
        className={inter.className + " bg-prim-950 h-full text-slate-50 p-6"}
      >
        <header>
          <Image
            src="/logo.png"
            alt="company logo"
            width={75}
            height={75}
            className="auto-fit"
          />
        </header>
        {children}
      </body>
    </html>
  );
}
